# Generated by Django 5.0.6 on 2024-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('platform', models.CharField(choices=[('Instagram', 'Instagram'), ('TikTok', 'TikTok'), ('UGC', 'User Generated Content')], max_length=20)),
            ],
        ),
    ]
